name: planbook_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  database_planbook_api:
    path: ../database_planbook_api
  drift: ^2.26.1
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  jiffy: ^6.4.3
  path_provider: ^2.1.5
  planbook_api:
    path: ../planbook_api
  planbook_core:
    path: ../planbook_core
  purchases_flutter: ^9.9.10
  rxdart: ^0.28.0
  shared_preferences: ^2.3.5
  supabase_flutter: ^2.9.1
  supabase_planbook_api:
    path: ../supabase_planbook_api
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
