name: home_widget
description: A plugin to provide a common interface for creating HomeScreen Widgets for Android and iOS.
version: 0.9.0
repository: https://github.com/ABausG/home_widget
funding:
  - https://github.com/sponsors/ABausG/
topics:
  - home-screen-widget
  - native
  - android
  - ios
documentation: https://docs.page/ABausG/home_widget

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.20.0-1.2.pre"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.3
  path_provider_platform_interface:
  plugin_platform_interface:

flutter:
  plugin:
    platforms:
      android:
        package: es.antonborri.home_widget
        pluginClass: HomeWidgetPlugin
      ios:
        pluginClass: HomeWidgetPlugin
