name: flutter_planbook
description: A Very Good Project created by Very Good CLI.
version: 2.0.0+55
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  animated_text_kit: ^4.3.0
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  calendar_date_picker2: ^2.0.1
  carousel_slider: ^5.1.1
  collection: ^1.19.1
  cupertino_calendar_picker: ^2.2.6
  cupertino_icons: ^1.0.6
  database_planbook_api:
    path: packages/database_planbook_api
  device_info_plus: ^12.2.0
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  email_validator: ^3.0.0
  equatable: ^2.0.7
  flex_color_picker: ^3.7.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_dynamic_icon_plus: ^1.3.1
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^19.3.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_slidable: ^4.0.3
  flutter_spinkit: ^5.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.11
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.3.0
  hydrated_bloc: ^10.1.1
  image_cropper: ^11.0.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.3
  in_app_review: ^2.0.10
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.2
  jiffy: ^6.3.1
  octo_image: ^2.1.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  planbook_api:
    path: packages/planbook_api
  planbook_core:
    path: packages/planbook_core
  planbook_repository:
    path: packages/planbook_repository
  pull_down_button: ^0.10.2
  purchases_flutter: 9.9.9
  rxdart: ^0.28.0
  screenshot: ^3.0.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.2.1
  sqlite3: ^2.7.7
  sqlite3_flutter_libs: ^0.5.37
  supabase_flutter: ^2.9.1
  supabase_planbook_api:
    path: packages/supabase_planbook_api
  tab_indicator_styler: ^2.0.0
  table_calendar: ^3.2.0
  timezone: ^0.10.1
  upgrader: ^12.3.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_test: ^10.0.0
  build_runner: ^2.4.2
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/files/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
