name: planbook_api
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.7
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  hive: ^2.2.3
  jiffy: ^6.4.3
  path: ^1.9.1
  path_provider: ^2.1.5
  path_provider_foundation: ^2.4.1
  planbook_core:
    path: ../planbook_core
  purchases_flutter: 9.9.9
  rxdart: ^0.28.0
  sign_in_with_apple: ^7.0.1
  sqlite3: ^2.7.6
  sqlite3_flutter_libs: ^0.5.34
  supabase_flutter: ^2.9.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
